CALLBACK_URL_DEFAULT: "https://apis-qa.alp-robinhood.com/logistic/delivery/update-delivery-status"
PRICINGSERVICE_BASE_PATH: "http://pricing-service.qa:8080"
RIDERPROFILE_SERVICE_BASE_PATH: "http://rider-service.qa:8080"
RHINTERFACE_SERVICE_EXTERNAL_BASE_URL: "https://rh-interface-service.api-qa.riderplatform.com"
LOCATION_SERVICE_BASE_PATH: "http://location-service.qa:8080"
OPERATIONS_PORTAL_BASE_PATH: "https://operations-portal.web-qa.riderplatform.com"
OPERATIONS_SERVICE_BASE_PATH: "http://operations-service.qa:8080"
CUSTOMER_PRICING_SERVICE_BASE_PATH: "http://customer-pricing-service.qa:8080"
REDIS_PRIMARY_HOST: rider-qa-elasticache-redis.l9akz6.ng.0001.apse1.cache.amazonaws.com
REDIS_READ_HOST: rider-qa-elasticache-redis-ro.l9akz6.ng.0001.apse1.cache.amazonaws.com