CALLBACK_URL_DEFAULT: "https://apis-test.alp-robinhood.com/logistic/delivery/update-delivery-status"
PRICINGSERVICE_BASE_PATH: "http://pricing-service.test:8080"
RIDERPROFILE_SERVICE_BASE_PATH: "http://rider-service.test:8080"
RHINTERFACE_SERVICE_EXTERNAL_BASE_URL: "https://rh-interface-service.api-test.riderplatform.com"
LOCATION_SERVICE_BASE_PATH: "http://location-service.test:8080"
OPERATIONS_PORTAL_BASE_PATH: "https://operations-portal.web-test.riderplatform.com"
OPERATIONS_SERVICE_BASE_PATH: "http://operations-service.test:8080"
CUSTOMER_PRICING_SERVICE_BASE_PATH: "http://customer-pricing-service.test:8080"
REDIS_PRIMARY_HOST: qa-env.l9akz6.ng.0001.apse1.cache.amazonaws.com
REDIS_READ_HOST: qa-env-ro.l9akz6.ng.0001.apse1.cache.amazonaws.com